SELECT * FROM sys.tables

SELECT * FROM Feminicidio_exemplo;

SELECT DISTINCT Count(ID_DELEGACIA) FROM Feminicidio_exemplo

SELECT COUNT(MES_ESTATISTICA), DP_CIRCUNSCRICAO FROM Feminicidio_exemplo
WHERE DP_CIRCUNSCRICAO LIKE '%OSASCO%'
GROUP BY DP_CIRCUNSCRICAO;


SELECT COUNT(ID_DELEGACIA) AS 'qtdDeIDS', DP_CIRCUNSCRICAO FROM Feminicidio_exemplo
GROUP BY DP_CIRCUNSCRICAO
ORDER BY DP_CIRCUNSCRICAO;


SELECT ID_DELEGACIA, DP_CIRCUNSCRICAO, ANO_BO FROM Feminicidio_exemplo
WHERE DP_CIRCUNSCRICAO = '047 DP - Capão Redondo'

SELECT * FROM Feminicidio_exemplo
WHERE ID_DELEGACIA = '10247';

SELECT DISTINCT ID_DELEGACIA, COUNT(ID_DELEGACIA) FROM Feminicidio_exemplo
GROUP BY ID_DELEGACIA;

SELECT DISTINCT MES_ESTATISTICA, ID_DELEGACIA, DP_CIRCUNSCRICAO
 FROM Feminicidio_exemplo;

SELECT  ID_DELEGACIA,COUNT(MES_ESTATISTICA) AS QUANTIDADE, MES_ESTATISTICA FROM Feminicidio_exemplo
 GROUP BY ID_DELEGACIA,MES_ESTATISTICA
 HAVING(MES_ESTATISTICA) = 1
 ORDER BY MES_ESTATISTICA


 SELECT * FROM Feminicidio_exemplo
 WHERE ID_DELEGACIA = '70014';
 